(in-package :smackfeebs2)


(defparameter *feeb-functions*
  '(
    (smacklisp::planet-name feebs:planet-name)    
    (smacklisp::feeb-heading feebs:feeb-heading)
    (smacklisp::feeb-name feebs:feeb-name)
    (smacklisp::set-feeb-name feebs:set-feeb-name)
    (smacklisp::coordinates feebs:coordinates)
    (smacklisp::feeb-peeking feebs:feeb-peeking)
    (smacklisp::feeb-energy feebs:feeb-energy)
    (smacklisp::line-of-sight feebs:line-of-sight)        
    (smacklisp::feeb-score feebs:feeb-score)
    (smacklisp::feeb-kills feebs:feeb-kills)
    (smacklisp::feeb-last-move feebs:feeb-last-move)
    (smacklisp::move-aborted-p feebs:move-aborted-p)
    (smacklisp::ready-to-fire-p feebs:ready-to-fire-p)
    (smacklisp::current-square feebs:current-square)
    (smacklisp::rear-square feebs:rear-square)
    (smacklisp::left-square feebs:left-square)
    (smacklisp::right-square feebs:right-square)
    (smacklisp::vision-ahead feebs:vision-ahead)
    (smacklisp::vision-right feebs:vision-right)
    (smacklisp::vision-left feebs:vision-left)
    (smacklisp::feeb-image-p feebs:feeb-image-p)
    (smacklisp::feeb-image-name feebs:feeb-image-name)
    (smacklisp::feeb-image-heading feebs:feeb-image-heading)
    (smacklisp::fireball-image-p feebs:fireball-image-p)
    (smacklisp::fireball-image-shooter feebs:fireball-image-shooter)
    (smacklisp::fireball-image-direction feebs:fireball-image-direction)
    (smacklisp::get-parm feebs:get-parm)
    (smacklisp::set-parm feebs:set-parm)
    (smacklisp::print-maze feebs:print-maze)
    (smacklisp::print-scoreboard feebs:print-scoreboard)
    (smacklisp::test-feeb-brain feebs:test-feeb-brain)
    (smacklisp::list-parameter-settings feebs:list-parameter-settings)
    (smacklisp::move feebs:move)
    (smacklisp::play-cycle feebs:play-cycle)
    (smacklisp::play-restart feebs:play-restart)
    (smacklisp::play-game feebs:play-game)
    (smacklisp::maze-layouts feebs:maze-layouts)
    (smacklisp::change-maze-layout feebs:change-maze-layout)
    (smacklisp::planet-list feebs:planet-list) 
    (smacklisp::planet-feebs feebs:planet-feebs) 
    (smacklisp::planet-create feebs:planet-create)
    (smacklisp::planet-join feebs:planet-join) 
    (smacklisp::planet-leave feebs:planet-leave)
    ))


(defun create-lisp-environment ()
  (let* ((env (make-hash-table))
         (smacklisp:*smack-symbols* env))
    (smacklisp:init-smack-interp)
    (mapc #'smacklisp::link-smack-cl-function *feeb-functions*)
    env))

(defun publish-feeb-brain (feeb brain)
  (setf (feebs-base::feeb-brain feeb)
        (let ((feebs::*active-feeb* feeb))
          (lambda ()
            (funcall brain)))))

(defun create-feeb (name)
  (let ((env (create-lisp-environment))
        (feeb (feebs:make-feeb name)))
    (setf (feebs-base::feeb-lisp-env feeb)
          env)
    (publish-feeb-brain feeb (lambda ()
            :wait))
    (setf (feebs-base::feeb-publish feeb)
          #'publish-feeb-brain)
    feeb))


(defun feeb-repl (feeb)
  (let ((feebs::*active-feeb* feeb))
    (clicl:repl (feebs-base::feeb-lisp-env feeb))))

(defun load-file (feeb file)
  (clicl:load-file (feebs-base::feeb-lisp-env feeb) file))
